name: 'Operator-SDK Action'
description: 'GitHub Actions for Operator-SDK build'
author: 'Michael Fornaro <michaelfornaro@gmail.com>'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  image:
    description: 'Image name'
    required: true
  tag:
    description: 'Image tag'
    required: false
  dirPath:
    description: 'Project structure requires build/Dockerfile'
    required: false
  args:
    description: 'Additional arguments passed to operator-sdk build'
    required: false
outputs:
  image:
    description: 'Built docker image name'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "${{ inputs.image }}"
    - "${{ inputs.tag }}"
    - "${{ inputs.dirPath }}"
    - "${{ inputs.goBuildArgs }}"
